# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-28 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqlength', models.IntegerField()),
                ('index', models.IntegerField()),
                ('sequence', models.CharField(max_length=50)),
            ],
        ),
    ]
